# Day 2 : Titanic Dataset

In [5]:
import pandas as pd
import numpy as np

data = pd.read_csv("train.csv")

## Question 1

In [32]:
total_females = data.groupby("Sex")['PassengerId'].count().iloc[0]
total_males = data.groupby("Sex")['PassengerId'].count().iloc[1]

survived_females = data.groupby("Sex")['Survived'].sum().iloc[0]
survived_males = data.groupby("Sex")['Survived'].sum().iloc[1]

print(f"1. Total Females = {total_females}")
print(f"2. Total Males = {total_males}")
print(f"3. Survived Females = {survived_females}")
print(f"4. Survived Males = {survived_males}")

1. Total Females = 314
2. Total Males = 577
3. Survived Females = 233
4. Survived Males = 109

## Question 2

In [71]:
multi_cond = data[data["Pclass"]==1].groupby("Sex")["Survived"].sum().iloc[0]
print(f"Number of female passengers in Pclass=1 who survived = {multi_cond}")

Number of female passengers in Pclass=1 who survived = 91

## Question 3

In [74]:
data.groupby("Sex").agg(Count = ('PassengerId','count'))

        Count
Sex
female    314
male      577

## Question 4

In [76]:
data.groupby("Pclass").agg(
    Avg_Age = ('Age','mean'),
    Median_Age = ("Age", 'median'),
    Max_Fare = ("Fare",'max'))

          Avg_Age  Median_Age  Max_Fare
Pclass
1       38.233441        37.0  512.3292
2       29.877630        29.0   73.5000
3       25.140620        24.0   69.5500

# Question 5

In [ ]:
print(f"1. Number of missing values in each column: \n{data.isna().sum()}")

#data.isna().agg(['sum'])
max_na = data.isna().sum().max() ## Use idxmax here
print(f"\n2. Highest number of missing values in a column = {max_na}") # I didnt know how to get the column name lol

percentage_na = max_na*100/len(data)
print(f"\n3. Percentage missing in that column = {percentage_na.round(4)}")

1. Number of missing values in each column:
PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

2. Highest number of missing values in a column = 687

3. Percentage missing in that column = 77.1044

## Question 6

In [ ]:
data['Age_Median_By_Class'] = data.groupby("Pclass")['Age'].transform("median")  #I had to search it up, cuz i kept getting confused
data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Median_By_Class
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,24.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,24.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,37.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,29.0
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,37.0
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S,24.0
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,37.0
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,24.0

## Question 7

In [155]:
data['Age_Filled'] = data['Age'].fillna(data['Age_Median_By_Class'])
print(f"Missing Before = {data['Age'].isna().sum()}")
print(f"Missing After = {data['Age_Filled'].isna().sum()}")

Missing Before = 177
Missing After = 0

## Question 8

In [163]:
def age_group(x):
    if x<18:
        return "Child"
    elif 18<=x<=59:
        return "Adult"
    elif x>=60:
        return "Senior"

data['Age_Group'] = data['Age_Filled'].apply(age_group)

data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_Median_By_Class,Age_Filled,Age_Group
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,24.0,22.0,Adult
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,37.0,38.0,Adult
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,24.0,26.0,Adult
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,37.0,35.0,Adult
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,24.0,35.0,Adult

## Question 9

In [167]:
data.groupby('Age_Group').agg(
    Passenger_Count = ("PassengerId",'count'),
    Survival_Rate = ("Survived", lambda x: round(x.mean()*100,2))
)

           Passenger_Count  Survival_Rate
Age_Group
Adult                  752          36.44
Child                  113          53.98
Senior                  26          26.92

## Question 10

In [ ]:
data['Fare'].idxmax()
data.iloc[258][['Name','Fare']]  # I had to look this up.

Name    Ward, Miss. Anna
Fare            512.3292
Name: 258, dtype: object